# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Source aliases
source $HOME/.zsh/aliases.zsh
source $HOME/.zsh/functions.zsh

# user scripts
export PATH="$HOME/bin:$PATH"

# needed by homebrew for some package executables
export PATH="/usr/local/sbin:$PATH"
export PATH="$HOME/.node/bin:$PATH"
export PATH="$HOME/.local/bin:$PATH"

setopt RM_STAR_WAIT           # pause before confirming rm *
setopt clobber                # turn off zsh: file exists warning

# nvm
export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion

# zoxide
eval "$(zoxide init zsh)"

# fzf
eval "$(fzf --zsh)"
[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
export FZF_DEFAULT_COMMAND='rg --files --hidden --follow --no-ignore-vcs'
export FZF_DEFAULT_OPTS='--height=70% --layout=reverse'
export FZF_CTRL_T_OPTS="
  --walker-skip .git,node_modules,target
  --preview 'bat -n --color=always {}'
  --bind 'ctrl-/:change-preview-window(down|hidden|)'"

# poetry
export PATH="$HOME/.poetry/bin:$PATH"
fpath+=~/.zfunc
autoload -Uz compinit && compinit