# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Source aliases
source $HOME/.zsh/aliases.zsh
source $HOME/.zsh/functions.zsh

# user scripts
export PATH="$HOME/bin:$PATH"

# needed by homebrew for some package executables
export PATH="/usr/local/sbin:$PATH"
export PATH="$HOME/.node/bin:$PATH"
export PATH="$HOME/.local/bin:$PATH"

setopt RM_STAR_WAIT           # pause before confirming rm *
setopt clobber                # turn off zsh: file exists warning

export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion

# Google Cloud 
# The next line updates PATH for the Google Cloud SDK.
if [ -f $HOME/bin/google-cloud-sdk/path.zsh.inc ]; then . $HOME/bin/google-cloud-sdk/path.zsh.inc; fi

# The next line enables shell command completion for gcloud.
if [ -f $HOME/bin/google-cloud-sdk/completion.zsh.inc ]; then . $HOME/bin/google-cloud-sdk/completion.zsh.inc; fi

export CLOUDSDK_PYTHON=python2

eval "$(zoxide init zsh)"

export PATH="$HOME/.poetry/bin:$PATH"

# fzf
[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
export FZF_DEFAULT_COMMAND='rg --files --hidden --follow --no-ignore-vcs'
# export FZF_CTRL_T_COMMAND="$FZF_DEFAULT_COMMAND"
export FZF_DEFAULT_OPTS='--height=70% --layout=reverse" --preview="bat --style=numbers --color=always {}"'

